# Run Github action and pass outputs between steps
# What it does:
#  - Pass outputs of steps into other steps
name: output-chain
on:
  workflow_dispatch:
    inputs:
      firstName:
        description: First Name
        required: false
      lastName:
        description: Last Name
        required: false

jobs:
  checking-outputs:
    runs-on: ubuntu-latest
    steps:
      - name: Generate output to file
        id: file-output
        # For shell based action. Set the output using workflow command
        run: |
          echo "${{ github.event.inputs.firstname }} ${{ github.event.inputs.lastName }}" > file-output.txt
          echo "::set-output name=filename::file-output.txt"
      - name: Retrieve output from file
        # Retrieve the output value from steps.<step-id>.output context
        run: cat "${{ steps.file-output.outputs.filename }}"

      - name: Formatting log output
        run: |
          echo "This is normal output"
          echo "To enable the following debug output, set ACTIONS_STEP_DEBUG in the repo secrets"
          echo "::debug::This is a debug message"
          echo "::warning::This is a warning message"
          echo "::group::This is a group title"
          cat << EOF
          This is some arbitrary multiline
          of log output
          or comments
          that is grouped together
          EOF
          echo "::endgroup::"